[package]
name = "shadow"
version = "0.1.0"
authors = ["clearloop <udtrokia@gmail.com>"]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies]
actix-web = "2.0.0"
blake2-rfc = "0.2.18"
cmmr = { version = "0.3.0", package = "ckb-merkle-mountain-range"}
dirs = "2.0.2"
env_logger = "0.7.1"
etc = "0.1.7"
libc = "0.2.71"
log = "0.4.0"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uint = "0.8.3"

[dependencies.scale]
package = "parity-scale-codec"
version = "1.0.112"
features = ["derive"]

[dependencies.diesel]
version = "1.4.4"
features = ["r2d2", "sqlite"]

[dependencies.eth]
git = "https://github.com/darwinia-network/darwinia-common.git"
package = "ethereum-primitives"
optional = true

[features]
darwinia = [ "eth" ]
default = []