[package]
name = "darwinia-shadow"
version = "0.0.1"
authors = ["clearloop <udtrokia@gmail.com>"]
edition = "2018"

[[bin]]
name = "shadow"
path = "src/bin/shadow.rs"

[lib]
path = "src/lib.rs"

[dependencies]
async-std = "1.6.3"
actix-web = "2.0.0"
actix-rt = "1.0"
blake2-rfc = "0.2.18"
cmmr = { version = "0.3.0", package = "ckb-merkle-mountain-range"}
dirs = "2.0.2"
env_logger = "0.7.1"
etc = "0.1.7"
futures = "0.3"
libc = "0.2.71"
log = "0.4.0"
reqwest = { version = "0.10", features = ["json"] }
rlp = "0.4.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3.17"
uint = "0.8.3"

[dependencies.scale]
package = "parity-scale-codec"
version = "1.0.112"
features = ["derive"]

[dependencies.diesel]
version = "1.4.4"
features = ["r2d2", "sqlite"]
