[package]
name = "mmr"
version = "0.1.0"
authors = ["clearloop <udtrokia@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
path = "mmr/lib.rs"
crate_type = ["rlib", "dylib"]

[dependencies]
dirs = "2.0.2"
etc = "0.1.7"
cmmr = { version = "0.3.0", package = "ckb-merkle-mountain-range"}
blake2b-rs = "0.1.5"

[dependencies.diesel]
version = "1.4.4"
features = ["sqlite"]

[profile.release]
debug = true