version: "3"
services:
  geth:
    image: ethereum/client-go:stable
    command: --syncmode fast --http --http.addr 0.0.0.0 -http.vhosts *
  fetcher:
    image: darwinianetwork/shadow:0.1.8
    command: run -v
    environment:
      - INFURA_KEY=8fdebe351ac94b62862b7c1d3798eb3a
      - ETHEREUM_RPC=http://geth:8545
    ports:
      - 3000:3000
    volumes:
      - data:/root/.darwinia
    depends_on:
      - geth
  mmr:
    image: darwinianetwork/shadow:0.1.8
    command: run -vm --no-fetch --no-api
    volumes:
      - data:/root/.darwinia
    depends_on:
      - fetcher

volumes:
  data:
