name: Clippy Check

on:
  push:
    branches: [ master, next ]
  pull_request:
    branches: [ master, next ]

jobs:
  clippy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Environment
        run: |
          if [[ "$(uname)" == 'Darwin' ]]; then
              brew update
              brew install sqlite3
          else
              sudo apt-get update -y
              sudo apt-get install -y libsqlite3-dev libdbus-1-dev
          fi
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
