# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Golang CI Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    # Checkout Go module directory
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    # Cache MMR Library
    - name: Cache MMR Library
      uses: actions/cache@v1
      env:
        cache-name: mmr-cache
      with:
        path: ./target
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./Cargo.lock') }}
        
    # Lint code
    - name: Lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.28
