# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Golang CI Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    # Set up golang env
    - name: Set up GO 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    # Checkout Go module directory
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    # Sqlite3 deps
    - name: Environment
      run: |
          if [[ "$(uname)" == 'Darwin' ]]; then
              brew update
              brew install sqlite3
          else
              sudo apt-get update -y
              sudo apt-get install -y libsqlite3-dev libdbus-1-dev
          fi
    # Get deps
    - name: Get dependencies
      run:  go mod download

    # Build packages
    - name: Build
      run: make

    # Lint code
    - uses: actions/checkout@v2
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v1
      with:
        version: v1.26
