name: Rust MMR

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  mmr:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    steps:
      - name: Checkout the source code
        uses: actions/checkout@master
      - name: Environment
        run: |
          if [[ "$(uname)" == 'Darwin' ]]; then
              brew update
              brew install sqlite3
          else
              sudo apt-get update -y
              sudo apt-get install -y libsqlite3-dev libdbus-1-dev
          fi
      # Cache MMR Library
      - name: Cache MMR Library
        uses: actions/cache@v1
        env:
          cache-name: mmr-cache
        with:
          path: ./target
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
