name: shadow

on:
  push:
    branches: [ master, next ]
  pull_request:
    branches: [ master, next ]

jobs:
  mmr:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    steps:
      - name: Checkout the source code
        uses: actions/checkout@master
      - name: Environment
        run: |
          if [[ "$(uname)" == 'Darwin' ]]; then
              brew update
              brew install sqlite3
          else
              sudo apt-get update -y
              sudo apt-get install -y libsqlite3-dev libdbus-1-dev
          fi
      # Cache MMR Library
      - name: Cache MMR Library
        uses: actions/cache@v1
        env:
          cache-name: mmr-cache
        with:
          path: ./target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./Cargo.lock') }}
      - name: Build
        run: cargo build --release -vv
      - name: Check Binary
        run: ./target/release/shadow version
      - name: Run tests
        run: cargo test --release -vv
