name: shadow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  mmr:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v1
      - name: Cache MMR Library
        uses: actions/cache@v1
        env:
          cache-name: mmr-cache
        with:
          path: ./target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./Cargo.lock') }}
      - name: Build
        run: cargo build --release -vv
      - name: Check Binary
        run: ./target/release/shadow --version
      - name: Run tests
        run: cargo test --release -vv
